### ISSUE TITLE
Fatal error: uncaught error – can some help me to solve this issue?

### ISSUE THREAD

**Issue by ghost** [times/acf-to-wp-api#61]
Fatal error: Uncaught Error: Call to undefined function get_field() in /home/.sites/869/site4366094/web/wavelife/wp-content/themes/proformat/functions.php:340 Stack trace: #0 /home/.sites/869/site4366094/web/wavelife/wp-settings.php(479): include() #1 /home/.sites/869/site4366094/web/wavelife/wp-config.php(90): require_once('/home/.sites/86...') #2 /home/.sites/869/site4366094/web/wavelife/wp-load.php(37): require_once('/home/.sites/86...') #3 /home/.sites/869/site4366094/web/wavelife/wp-blog-header.php(13): require_once('/home/.sites/86...') #4 /home/.sites/869/site4366094/web/wavelife/index.php(17): require('/home/.sites/86...') #5 {main} thrown in /home/.sites/869/site4366094/web/wavelife/wp-content/themes/proformat/functions.php on line 340

**Comment by klaudiomilankovic** [comment]
Do you have Advanced Custom Fields plugin installed and activated?
